version: '3'

services:
  website:
    build:
      context: /web
      dockerfile: Dockerfile
    image: site
    ports:
      - "8501:8501"
  api:
    build:
      context: /
      dockerfile: /api/Dockerfile
    image: api
    ports:
      - "80:80"